#!/system/bin/sh

## These are some comments to fill up space that would otherwise be used 
## in this file. Since I am one for the classics, I will fill the rest of 
## the empty space with lorem ipsum.. please enjoy.

## Lorem ipsum dolor sit amet, id sea nostrud inimicus, nec in feugiat 
## accusata. Mei no everti dignissim percipitur. Cu cum ludus intellegebat. 
## Vix in vocent audiam. Eu dolorum fabellas disputationi qui, vim at ullum 
## omittantur instructior. Has tempor quaeque ut, ex iusto populo omittantur 
## nec, tacimates inimicus scripserit in usu.

## Ad unum paulo qui, bonorum invidunt mea an. Delicata comprehensam eu mei, 
## nam ex homero malorum, tale constituam ex vel. Nulla conceptam in vim. 
## Quaeque delectus consulatu eu eos, duo id diam commodo, est quando 
## pertinacia signiferumque ei. Ut definiebas vituperata pro, eu sed habeo 
## tacimates.

## Minim sapientem vel id, perfecto repudiare ne nam, quo ipsum omnesque 
## pericula ea. Ne facer gloriatur vix. An dicit timeam sea, ea eam civibus 
## nostrum elaboraret. Facer discere mel in. Vel at albucius senserit, cu 
## tempor recusabo sea.

## Nec solum ridens sapientem an. Ut duis minimum conceptam has. No duo esse 
## dicta commodo. At qui admodum apeirian, ad percipit disputando omittantur 
## vim.

# trigger the toolbox
/system/bin/ls 

